"""add owner_id to jobs

Revision ID: 91fe6c939bb0
Revises: cbef5bcbfb6f
Create Date: 2026-01-26 23:02:23.460299

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91fe6c939bb0"
down_revision: Union[str, Sequence[str], None] = "cbef5bcbfb6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("owner_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_jobs_owner_id"), "jobs", ["owner_id"], unique=False)
    op.create_foreign_key(None, "jobs", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "jobs", type_="foreignkey")
    op.drop_index(op.f("ix_jobs_owner_id"), table_name="jobs")
    op.drop_column("jobs", "owner_id")
    # ### end Alembic commands ###
