"""Add foreign keys and indexes

Revision ID: cbef5bcbfb6f
Revises: 
Create Date: 2026-01-22 20:07:57.062402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbef5bcbfb6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applicants_applied_at'), 'applicants', ['applied_at'], unique=False)
    op.create_index(op.f('ix_applicants_email'), 'applicants', ['email'], unique=False)
    op.create_index('ix_applicants_email_job', 'applicants', ['email', 'job_id'], unique=True)
    op.create_index('ix_applicants_job_score', 'applicants', ['job_id', 'similarity_score'], unique=False)
    op.create_index('ix_applicants_job_shortlist', 'applicants', ['job_id', 'shortlisted'], unique=False)
    op.create_index(op.f('ix_applicants_similarity_score'), 'applicants', ['similarity_score'], unique=False)
    op.create_foreign_key(None, 'applicants', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_interviews_job_status', 'interviews', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_foreign_key(None, 'interviews', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interviews', 'applicants', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_current_node'), 'jobs', ['current_node'], unique=False)
    op.create_index('ix_jobs_node_created', 'jobs', ['current_node', 'created_at'], unique=False)
    op.create_index('ix_responses_candidate_job', 'prescreening_responses', ['candidate_id', 'job_id'], unique=False)
    op.create_foreign_key(None, 'prescreening_responses', 'applicants', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescreening_responses', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescreening_responses', type_='foreignkey')
    op.drop_constraint(None, 'prescreening_responses', type_='foreignkey')
    op.drop_index('ix_responses_candidate_job', table_name='prescreening_responses')
    op.drop_index('ix_jobs_node_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_current_node'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index('ix_interviews_job_status', table_name='interviews')
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    op.drop_index(op.f('ix_applicants_similarity_score'), table_name='applicants')
    op.drop_index('ix_applicants_job_shortlist', table_name='applicants')
    op.drop_index('ix_applicants_job_score', table_name='applicants')
    op.drop_index('ix_applicants_email_job', table_name='applicants')
    op.drop_index(op.f('ix_applicants_email'), table_name='applicants')
    op.drop_index(op.f('ix_applicants_applied_at'), table_name='applicants')
    # ### end Alembic commands ###
